Fix linter errors caused by upstream changes. (#216)
### Description

Fixes linter errors caused by [upstream changes](https://github.com/dbt-labs/dbt-core/pull/5954).

```
dbt/adapters/databricks/connections.py:440: error: Argument "conn_name" to "ConnectionUsed" has incompatible type "Optional[str]"; expected "str"  [arg-type]
dbt/adapters/databricks/connections.py:449: error: Argument "conn_name" to "SQLQuery" has incompatible type "Optional[str]"; expected "str"  [arg-type]
dbt/adapters/databricks/connections.py:491: error: Argument "conn_name" to "ConnectionUsed" has incompatible type "Optional[str]"; expected "str"  [arg-type]
dbt/adapters/databricks/connections.py:496: error: Argument "conn_name" to "SQLQuery" has incompatible type "Optional[str]"; expected "str"  [arg-type]
```