Fix cancellation. (#173)
### Description

`DatabricksSQLConnectionWrapper` should have `cancel` method and handle it properly.

Otherwise, the following error will be seen when cancelling the session due to e.g., `dbt test --fail-fast`:

```
AttributeError: 'DatabricksSQLConnectionWrapper' object has no attribute 'cancel'
```