Fix integration test failures. (#8)
Fix integration test failures.

There are a couple of tests which came to fail after changing the default file format to 'delta'.

```
============================================================================= short test summary info ==============================================================================
FAILED tests/integration/incremental_strategies/test_incremental_strategies.py::TestInsertOverwrite::test_insert_overwrite_databricks_sql_connector - AssertionError: False != Tr...
FAILED tests/integration/incremental_strategies/test_incremental_strategies.py::TestBadStrategies::test_bad_strategies_databricks_sql_connector - AssertionError: 'error' != <Run...
============================================================== 2 failed, 10 passed, 622 warnings in 218.41s (0:03:38) ==============================================================
```

Because they assume the file format is 'parquet' that used to be the default.